/* CTS Business Intelligence Portal - the monthly email
 * ---------------------------------------------------------------------------
 * Renders the month as email, one per recipient, in three tiers:
 *
 *   1  Executive         the whole company: result, departments after the
 *                        overhead split, top clients under the four headings,
 *                        utilisation, and what is worth a comment
 *   2  Department head   their own department in depth, one line on the rest
 *   3  Finance           the controls: does the ledger tie, what is uncoded,
 *                        what rests on a placeholder, what the build did
 *
 * Sending is deliberately separate from rendering. The portal writes the
 * messages into outbox/YYYY-MM as JSON and HTML, and whatever sends them
 * (a Power Automate flow, later Graph) reads that folder. Nothing goes out
 * without somebody having clicked Build first, which is the same decision
 * O33 made: automated scheduling risks distributing unreviewed data.
 */
(function () {
  "use strict";
  var CTS = (window.CTS = window.CTS || {});
  var M = (CTS.email = {});
  var F = function () { return CTS.fmt; };
  var E = function () { return CTS.engine; };

  M.TIERS = { 1: "Executive", 2: "Department head", 3: "Finance" };

  M.recipients = function () {
    var cfg = E().cfg || {};
    return (cfg.DISTRIBUTION || []).filter(function (r) { return r.send !== false; });
  };

  /* ---- email safe HTML: tables and inline styles, nothing else ---------- */
  var FONT = "font-family:Arial,Helvetica,sans-serif;";
  function esc(s) { return String(s == null ? "" : s).replace(/[&<>]/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c]; }); }
  function h1(t) { return '<h1 style="' + FONT + 'font-size:20px;color:#181818;margin:0 0 4px">' + esc(t) + "</h1>"; }
  function h2(t) { return '<h2 style="' + FONT + 'font-size:15px;color:#181818;margin:22px 0 8px;border-bottom:2px solid #14a3a3;padding-bottom:4px">' + esc(t) + "</h2>"; }
  function p(t, muted) { return '<p style="' + FONT + 'font-size:13px;color:' + (muted ? "#595959" : "#232321") + ';margin:6px 0;line-height:1.45">' + t + "</p>"; }
  function table(cols, rows) {
    var out = '<table cellpadding="0" cellspacing="0" style="border-collapse:collapse;width:100%;max-width:720px;' + FONT + 'font-size:12.5px">';
    out += "<tr>" + cols.map(function (c) {
      return '<th style="text-align:' + (c.align || "right") + ';padding:6px 8px;background:#f2f2f2;color:#595959;font-size:11px;text-transform:uppercase;border-bottom:1px solid #dcdcd7">' + esc(c.label) + "</th>";
    }).join("") + "</tr>";
    rows.forEach(function (r) {
      out += '<tr>' + cols.map(function (c) {
        var v = typeof c.value === "function" ? c.value(r) : r[c.key];
        var txt = c.fmt ? c.fmt(v) : esc(v == null ? "-" : v);
        var neg = typeof v === "number" && v < 0 && c.fmt;
        return '<td style="text-align:' + (c.align || "right") + ';padding:5px 8px;border-bottom:1px solid #eeeeeb;' +
               (r._bold ? "font-weight:bold;background:#f7f7f5;" : "") + (neg ? "color:#b3261e;" : "") + '">' + txt + "</td>";
      }).join("") + "</tr>";
    });
    return out + "</table>";
  }
  function money(c) { return esc(F().money(c)); }
  function pct(x) { return esc(F().pct(x)); }
  function chip(t, tone) {
    var bg = { good: "#e3f5e3", warn: "#fff1cc", bad: "#fbe3e3", muted: "#eeeeeb" }[tone || "muted"];
    return '<span style="display:inline-block;padding:1px 7px;border-radius:9px;background:' + bg + ';font-size:11px;font-weight:bold;' + FONT + '">' + esc(t) + "</span>";
  }
  function shell(title, sub, body) {
    return '<!DOCTYPE html><html><head><meta charset="utf-8"><title>' + esc(title) + '</title></head>' +
      '<body style="margin:0;padding:0;background:#f4f4f2"><div style="max-width:760px;margin:0 auto;padding:22px 20px;background:#ffffff">' +
      '<div style="border-left:4px solid #14a3a3;padding-left:12px;margin-bottom:14px">' + h1(title) + p(esc(sub), true) + "</div>" +
      body +
      '<p style="' + FONT + 'font-size:11px;color:#7b7a75;margin-top:28px;border-top:1px solid #dcdcd7;padding-top:10px">' +
      "Generated by the CTS Business Intelligence Portal from the templates in the portal folder. " +
      "Figures are as at the build shown above; open the portal for the live view.</p></div></body></html>";
  }

  /* ---- the pieces --------------------------------------------------------- */
  function companyBlock(keys, label) {
    var e = E(), pnl = e.pnlActual(keys), bud = e.pnlBudget(keys), prior = e.pnlActual(e.priorYearMonths(keys));
    var rows = [
      ["Revenue", pnl.totals.income, bud.totals.income, prior.totals.income],
      ["Cost of sales", pnl.totals.cos, bud.totals.cos, prior.totals.cos],
      ["Gross profit", pnl.totals.grossProfit, bud.totals.grossProfit, prior.totals.grossProfit, true],
      ["Overheads", pnl.totals.expenses, bud.totals.expenses, prior.totals.expenses],
      ["Other income", pnl.totals.otherIncome, bud.totals.otherIncome, prior.totals.otherIncome],
      ["Net profit", pnl.totals.netProfit, bud.totals.netProfit, prior.totals.netProfit, true],
    ].map(function (r) { return { l: r[0], a: r[1], b: r[2], py: r[3], v: r[1] - r[2], _bold: !!r[4] }; });
    var gm = pnl.totals.income ? pnl.totals.grossProfit / pnl.totals.income : null;
    var outlook = "";
    if (e.forecastEnabled && e.forecastEnabled()) {
      var fyK = e.monthsOfFY(e.currentFY()), land = e.pnlBlend(fyK).totals, fb = e.pnlBudget(fyK).totals;
      outlook = p("<b>Full year FY" + e.currentFY() + " outlook:</b> revenue " + money(land.income) + " against budget " + money(fb.income) +
                  ", net profit " + money(land.netProfit) + " against budget " + money(fb.netProfit) +
                  ". Actual to date then forecast, line by line on the methods set for the month.");
      if (e.cashEnabled && e.cashEnabled()) {
        var c = e.cashflow();
        if (c) outlook += p("<b>Cash:</b> " + money(c.opening) + " at month end, low point " + money(c.low.closing) + " in " + esc(c.low.label) +
                            ", " + money(c.closing) + " in twelve months. Credit cards owing " + money(c.cardOwing) + ".");
      }
    }
    return h2("Company result, " + label) +
      table([{ key: "l", label: "", align: "left" }, { key: "a", label: "Actual", fmt: money },
             { key: "b", label: "Budget", fmt: money }, { key: "v", label: "Variance", fmt: money },
             { key: "py", label: "Last year", fmt: money }], rows) +
      p("Gross margin " + pct(gm) + ". Compared in dollars rather than percentages, as management prefer.", true) + outlook;
  }

  function deptBlock(keys, label, only) {
    var e = E(), alloc = e.allocate(keys);
    var rows = alloc.rows.filter(function (r) { return r.dept.isRevenue && (r.income || r.expenses); })
      .filter(function (r) { return !only || r.code === only; })
      .map(function (r) {
        var norm = r.dept.gmNorm;
        return { d: r.dept.short, rev: r.income, gm: r.gmPct, own: r.ownExpenses, share: r.allocated, np: r.netProfit,
                 flag: norm != null && r.gmPct != null && r.gmPct < norm ? chip("below " + F().pct(norm, 0) + " norm", "warn") : chip("ok", "good") };
      });
    var s = e.allocationIsSourced();
    return h2((only ? "Your department" : "Departments after the overhead split") + ", " + label) +
      table([{ key: "d", label: "Department", align: "left" }, { key: "rev", label: "Revenue", fmt: money },
             { key: "gm", label: "GM %", fmt: pct }, { key: "own", label: "Own overhead", fmt: money },
             { key: "share", label: "Share of Admin", fmt: money }, { key: "np", label: "Net profit", fmt: money },
             { key: "flag", label: "", align: "left", fmt: function (v) { return v; } }], rows) +
      (s.ok ? "" : p(chip("placeholder", "warn") + " The " + esc(s.placeholders.join(" and ")) + " split percentages are placeholders. Allocated figures move when they are confirmed.", true));
  }

  function oneLiners(keys, except) {
    var e = E(), alloc = e.allocate(keys);
    var lines = alloc.rows.filter(function (r) { return r.dept.isRevenue && r.code !== except && r.income; })
      .map(function (r) { return esc(r.dept.short) + " " + money(r.income) + " revenue, " + pct(r.gmPct) + " margin"; });
    return h2("The other departments, one line each") + p(lines.join("<br>"));
  }

  function clientsBlock(keys) {
    var e = E(), rows = e.clientRows(keys, e.priorYearMonths(keys)).filter(function (r) { return r.amount || r.prior; });
    var head = (e.cfg.COMMENTARY || {}).topClientHeadings || ["Revenue increased", "Revenue decreased", "New to the list", "Dropped off the list"];
    var inc = rows.filter(function (r) { return r.prior && r.delta > 0; }).slice(0, 5);
    var dec = rows.filter(function (r) { return r.prior && r.delta < 0; }).sort(function (a, b) { return a.delta - b.delta; }).slice(0, 5);
    var nw = rows.filter(function (r) { return r.amount && !r.prior; }).slice(0, 5);
    var dr = rows.filter(function (r) { return !r.amount && r.prior; }).slice(0, 5);
    function list(t, items, key) {
      return "<b>" + esc(t) + "</b><br>" + (items.length ? items.map(function (r) { return esc(r.display) + " " + money(r[key]); }).join("<br>") : "None") + "<br><br>";
    }
    return h2("Top clients, against the same period last year") +
      table([{ key: "rank", label: "#", align: "left" }, { key: "display", label: "Client", align: "left" },
             { key: "amount", label: "This period", fmt: money }, { key: "prior", label: "Last year", fmt: money },
             { key: "delta", label: "Variance", fmt: money }], rows.slice(0, 10)) +
      p(list(head[0], inc, "delta") + list(head[1], dec, "delta") + list(head[2], nw, "amount") + list(head[3], dr, "prior"));
  }

  function utilBlock(keys, only) {
    var e = E(), u = e.utilFor(keys), roll = e.utilRolling(keys[keys.length - 1]);
    var rows = u.rows.filter(function (r) { return r.total && (!only || r.code === only); }).map(function (r) {
      return { d: r.dept.short, c: r.chargeable, n: r.nonChargeable, u: r.util, t: r.target,
               gap: r.gap, fte: r.fte, flag: r.gap != null && r.gap < -0.05 ? chip("under target", "warn") : "" };
    });
    return h2("Utilisation" + (only ? "" : ", all departments")) +
      table([{ key: "d", label: "Department", align: "left" }, { key: "c", label: "Chargeable", fmt: function (v) { return esc(F().hours(v)); } },
             { key: "n", label: "Non-charge", fmt: function (v) { return esc(F().hours(v)); } }, { key: "u", label: "Util", fmt: pct },
             { key: "t", label: "Target", fmt: function (v) { return v == null ? "-" : esc(F().pct(v, 0)); } },
             { key: "fte", label: "FTE", fmt: function (v) { return v == null ? "-" : v.toFixed(2); } },
             { key: "flag", label: "", align: "left", fmt: function (v) { return v; } }], rows) +
      p("Rolling twelve months " + pct(roll.total.util) + " on " + esc(F().num(roll.annualHours)) + " hours" +
        (roll.annualCheck ? ", which lands on the 2,080 or 2,088 the graphs file expects." : ", which does not land on 2,080 or 2,088; check the Days tab.") +
        " Read a small negative before flagging it: for a team whose hours are almost all chargeable it usually means leave.", true);
  }

  function actionsBlock(keys) {
    var e = E(), act = e.pnlActual(keys), bud = e.pnlBudget(keys), items = [];
    act.cats.forEach(function (cat) {
      var bcat = bud.by[cat.key];
      cat.children.forEach(function (sub) {
        var bs = (bcat.children || []).filter(function (x) { return x.sub === sub.sub; })[0];
        var b = bs ? bs.total : 0;
        if (e.risk(sub.total, b) === "High") items.push({ w: cat.label + ": " + sub.sub, a: sub.total, b: b, v: sub.total - b });
      });
    });
    items.sort(function (a, b) { return Math.abs(b.v) - Math.abs(a.v); });
    return h2("Worth a comment") + (items.length ?
      table([{ key: "w", label: "Line", align: "left" }, { key: "a", label: "Actual", fmt: money },
             { key: "b", label: "Budget", fmt: money }, { key: "v", label: "Variance", fmt: money }], items.slice(0, 12)) +
      p("High risk on the Controller Pack's thresholds. Commentary explains the variance rather than restating it; for consulting, say whether a deal was lost or moved.", true)
      : p("Nothing above the high risk thresholds this period.", true));
  }

  function controlsBlock(keys, log) {
    var e = E(), pc = e.plCheck(keys), q = e.quality, s = e.allocationIsSourced();
    var rows = pc.map(function (r) { return { c: r.label, gl: r.gl, pl: r.pl, d: r.diff, s: r.ok ? chip("OK", "good") : chip("CHECK", "bad") }; });
    var body = h2("Does the ledger agree with the P&L") +
      table([{ key: "c", label: "Category", align: "left" }, { key: "gl", label: "Ledger", fmt: money },
             { key: "pl", label: "P&L", fmt: money }, { key: "d", label: "Difference", fmt: money },
             { key: "s", label: "", align: "left", fmt: function (v) { return v; } }], rows) +
      h2("Coding quality") +
      p("Ledger lines " + esc(F().num(q.rows)) + ", " + esc(F().date(q.minDate)) + " to " + esc(F().date(q.maxDate)) + ".<br>" +
        "Lines with no department: <b>" + q.noDept + "</b>. On an unknown account: <b>" + q.unknownAcct + "</b>. Revenue lines with no contact: <b>" + q.noContact + "</b>.") +
      h2("What the figures rest on") +
      p(s.ok ? chip("confirmed", "good") + " All three split bases are confirmed."
             : chip("placeholder", "warn") + " " + esc(s.placeholders.join(" and ")) + " split percentages are placeholders. Every allocated departmental figure depends on them.");
    if (log && log.checks) {
      body += h2("The build") + p((log.checks || []).map(function (c) {
        return chip(c.level, c.level === "ok" ? "good" : c.level === "fail" ? "bad" : c.level === "warn" ? "warn" : "muted") + " <b>" + esc(c.area) + "</b> " + esc(c.text);
      }).join("<br>"));
    }
    return body;
  }

  /* ---- one message per recipient ------------------------------------------ */
  /** Published commentary for the month, for the pages a tier reads. */
  function commentaryBlock(pages, dept) {
    var e = E(), rm = e.reportingMonth();
    if (!e.commentaryFor) return "";
    var items = [];
    pages.forEach(function (pg) {
      e.commentaryFor(pg, rm, { all: true }).forEach(function (c) {
        if (c.draft) return;
        if (dept && c.dept && c.dept !== dept) return;
        items.push(Object.assign({ pageTitle: (window.CTS.pages && window.CTS.pages[pg] ? window.CTS.pages[pg].title : pg) }, c));
      });
    });
    if (!items.length) return "";
    return h2("Commentary") + items.map(function (c) {
      return p("<b>" + esc(c.pageTitle) + (c.dept ? ", " + esc((e.deptOf[c.dept] || {}).short || c.dept) : "") + "</b> " +
               esc(c.text).replace(/\n/g, "<br>") + ' <span style="color:#595959">' + esc(c.author) + "</span>");
    }).join("");
  }
  M.commentaryBlock = commentaryBlock;

  M.render = function (recipient, opts) {
    opts = opts || {};
    var e = E(), keys = opts.keys || e.ytd(), rm = e.reportingMonth();
    var label = "FY" + e.currentFY() + " to " + ((e.monthIdx[rm] || {}).label || rm);
    var monthLong = (e.monthIdx[rm] || {}).long || rm;
    var tier = +recipient.tier || 3, body = "", subject;
    if (tier === 1) {
      subject = "CTS monthly result, " + monthLong;
      body = companyBlock(keys, label) + commentaryBlock(["home", "pnl", "forecast", "cash", "rev-summary", "rev-forecast", "bva"]) + deptBlock(keys, label) + clientsBlock(keys) + utilBlock(keys) + actionsBlock(keys);
    } else if (tier === 2) {
      var d = recipient.dept || null;
      var dn = d && e.deptOf[d] ? e.deptOf[d].short : "your department";
      subject = "CTS " + dn + " result, " + monthLong;
      body = deptBlock(keys, label, d) + commentaryBlock(["pnl-dept", "rev-schedule", "rev-forecast", "util", "pipeline"], d) + utilBlock(keys, d) + oneLiners(keys, d);
    } else {
      subject = "CTS month end controls, " + monthLong;
      body = controlsBlock(keys, opts.log) + companyBlock(keys, label) + commentaryBlock(Object.keys(window.CTS.pages || {}));
    }
    var html = shell(subject, "For " + recipient.name + " (" + M.TIERS[tier] + "). Built " + new Date().toISOString().slice(0, 10) + ".", body);
    var text = html.replace(/<style[\s\S]*?<\/style>/g, "").replace(/<\/(p|tr|h1|h2|div)>/g, "\n").replace(/<[^>]+>/g, "").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/\n{3,}/g, "\n\n").trim();
    return { to: recipient.email || "", name: recipient.name, tier: tier, subject: subject, html: html, text: text };
  };

  M.renderAll = function (opts) {
    return M.recipients().map(function (r) { return M.render(r, opts); });
  };

  /** The one dispatch that needs nothing: hand the message to the mail
   *  client. mailto carries plain text only and browsers cap its length, so
   *  the body is a summary with a pointer to the outbox HTML. */
  M.mailto = function (msg) {
    var body = msg.text.length > 1800 ? msg.text.slice(0, 1800) + "\n\n[Full report in the portal outbox]" : msg.text;
    return "mailto:" + encodeURIComponent(msg.to) + "?subject=" + encodeURIComponent(msg.subject) + "&body=" + encodeURIComponent(body);
  };
})();
