table Dim_Job

	column 'Job No'
		dataType: int64
		summarizeBy: none
		sourceColumn: Job No

	column 'Job Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Job Name

	column Chargeable
		dataType: string
		summarizeBy: none
		sourceColumn: Chargeable

	column 'Billing Basis'
		dataType: string
		summarizeBy: none
		sourceColumn: Billing Basis

	column 'Job Group'
		dataType: string
		summarizeBy: none
		sourceColumn: Job Group

	column 'First Booked'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: First Booked

	column 'Last Booked'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Last Booked

	column 'Total Hours'
		dataType: double
		summarizeBy: sum
		sourceColumn: Total Hours

	column 'Last Fully Billed Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Last Fully Billed Date

	column 'Override Billing Basis'
		dataType: string
		summarizeBy: none
		sourceColumn: Override Billing Basis

	column 'Billing Basis Final'
		dataType: string
		summarizeBy: none
		sourceColumn: Billing Basis Final

	partition Dim_Job = m
		mode: import
		source =
			let
			    Src   = Csv.Document(File.Contents(Text.TrimEnd(MappingFolderPath,"\") & "\map_jobs.csv"),
			                         [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Head  = Table.PromoteHeaders(Src, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Head, {
			               {"Job No", Int64.Type}, {"Job Name", type text}, {"Chargeable", type text},
			               {"Billing Basis", type text}, {"Job Group", type text},
			               {"First Booked", type date}, {"Last Booked", type date},
			               {"Last Fully Billed Date", type date}, {"Override Billing Basis", type text}}, "en-AU"),
			    // a manual override always wins over the derived basis
			    Final = Table.AddColumn(Typed, "Billing Basis Final",
			               each if [Override Billing Basis] <> null and Text.Trim([Override Billing Basis]) <> ""
			                    then Text.Trim([Override Billing Basis]) else [Billing Basis], type text),
			    Uniq  = Table.Distinct(Final, {"Job No"})
			in
			    Uniq
